#!/usr/bin/env python3
import csv
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

ROOT = Path('/Users/benselby/Development/Finances/finances')
CSV_PATH = ROOT / 'manatee-towers_2026-05-16_export.csv'
OUT_SQL = ROOT / 'supabase' / 'imports' / '20260516_historic_payments_import.sql'

PARTICIPANTS = ['Louise Billingham', 'Ben Selby']

CATEGORY_MAP = {
    'Mortgage': ('mortgage_rent', 'Mortgage / Rent', 'house', 20),
    'Rent': ('mortgage_rent', 'Mortgage / Rent', 'house', 20),
    'Insurance': ('insurance', 'Insurance', 'shield', 30),
    'Plane': ('travel', 'Travel', 'plane', 40),
    'Taxi': ('transport', 'Transport', 'car', 90),
    'Car': ('transport', 'Transport', 'car', 90),
    'Dining out': ('dining', 'Dining', 'utensils', 130),
    'Groceries': ('groceries', 'Groceries', 'basket', 50),
    'TV/Phone/Internet': ('internet_phone', 'Internet / Phone', 'wifi', 70),
    'Electricity': ('utilities', 'Utilities', 'zap', 60),
    'Household supplies': ('household_bills', 'Household Bills', 'home', 10),
    'Home - Other': ('household_bills', 'Household Bills', 'home', 10),
    'Music': ('subscriptions', 'Subscriptions', 'repeat', 80),
}


def q(text: str) -> str:
    return "'" + text.replace("'", "''") + "'"


def slugify(text: str) -> str:
    s = ''.join(ch.lower() if ch.isalnum() else '_' for ch in text.strip())
    while '__' in s:
        s = s.replace('__', '_')
    s = s.strip('_')
    return s or 'other'


with CSV_PATH.open(newline='', encoding='utf-8-sig') as f:
    reader = csv.DictReader(f)
    rows = [r for r in reader if (r.get('Date') or '').strip() and (r.get('Cost') or '').strip()]

# collect categories
categories = {}
for r in rows:
    raw = (r.get('Category') or '').strip()
    if not raw:
        raw = 'Other'
    if raw in CATEGORY_MAP:
        categories[raw] = CATEGORY_MAP[raw]
    else:
        key = slugify(raw)
        categories[raw] = (key, raw, 'circle', 900)

lines = []
lines.append('-- Generated by scripts/generate_historic_import_sql.py')
lines.append('begin;')
lines.append('')
lines.append('-- Preconditions: household exists and members include display names used below')
lines.append('with target_household as (')
lines.append('  select id from finance_app.households order by created_at asc limit 1')
lines.append('), required_members as (')
lines.append("  select hm.display_name from finance_app.household_members hm join target_household th on th.id = hm.household_id where hm.display_name in ('Louise Billingham', 'Ben Selby')")
lines.append("select case when (select count(*) from target_household)=0 then pg_catalog.raise_exception('No household found in finance_app.households') else 1 end;")
lines.append('')
lines.append('-- Ensure any missing source categories exist')
for raw, (key, label, icon, order) in sorted(categories.items(), key=lambda x: x[1][0]):
    lines.append(
        f"insert into finance_app.categories (key, label, icon_key, sort_order, is_active) values ({q(key)}, {q(label)}, {q(icon)}, {order}, true) on conflict (key) do update set label = excluded.label;"
    )
lines.append('')

for i, r in enumerate(rows, start=1):
    date = r['Date'].strip()
    desc = (r.get('Description') or '').strip() or 'Imported payment'
    raw_category = (r.get('Category') or '').strip() or 'Other'
    category_key = categories[raw_category][0]
    currency = (r.get('Currency') or 'GBP').strip().upper()
    cost = Decimal((r['Cost'] or '0').strip())
    cost2 = cost.quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)

    lou = Decimal((r.get('Louise Billingham') or '0').strip())
    ben = Decimal((r.get('Ben Selby') or '0').strip())

    source_type = 'settlement' if raw_category.lower() == 'payment' else 'one_off'

    # choose payer (positive net column) fallback Louise
    if lou > ben:
        payer_name = 'Louise Billingham'
        other_name = 'Ben Selby'
    else:
        payer_name = 'Ben Selby'
        other_name = 'Louise Billingham'

    if source_type == 'settlement':
        contrib_rows = [(payer_name, cost2)]
        split_rows = [(other_name, cost2)]
    else:
        half = (cost / Decimal('2')).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        remainder = cost2 - half
        contrib_rows = [(payer_name, cost2)]
        # split equally with rounding remainder on payer to keep totals exact
        split_rows = [(payer_name, remainder), (other_name, half)]

    lines.append(f'-- Row {i}: {date} {desc}')
    lines.append('with')
    lines.append('  th as (select id from finance_app.households order by created_at asc limit 1),')
    lines.append('  actor as (select id from auth.users order by created_at asc limit 1),')
    lines.append('  payer as (select user_id from finance_app.household_members hm join th on hm.household_id = th.id where hm.display_name = ' + q(payer_name) + ' limit 1),')
    lines.append('  other_member as (select user_id from finance_app.household_members hm join th on hm.household_id = th.id where hm.display_name = ' + q(other_name) + ' limit 1),')
    lines.append('  ins_payment as (')
    lines.append('    insert into finance_app.payments (household_id, title, amount, currency_code, fx_rate_to_gbp, fx_rate_date, amount_gbp, payment_date, category_key, notes, source_type, created_by)')
    lines.append('    select th.id, ' + q(desc) + f', {cost2}, ' + q(currency) + f", 1, {q(date)}, {cost2}, {q(date)}, {q(category_key)}, null, {q(source_type)}" + ', actor.id')
    lines.append('    from th, actor')
    lines.append('    returning id')
    lines.append('  )')

    contrib_values = []
    for name, amt in contrib_rows:
        member_cte = 'payer' if name == payer_name else 'other_member'
        contrib_values.append(f"select ins_payment.id, {member_cte}.user_id, {amt} from ins_payment, {member_cte}")
    lines.append('insert into finance_app.payment_contributions (payment_id, user_id, amount)')
    lines.append('  ' + '\n  union all\n  '.join(contrib_values) + ';')

    split_values = []
    for name, amt in split_rows:
        member_cte = 'payer' if name == payer_name else 'other_member'
        split_values.append(f"select ins_payment.id, {member_cte}.user_id, {amt} from ins_payment, {member_cte}")
    lines.append('insert into finance_app.payment_splits (payment_id, user_id, amount)')
    lines.append('  ' + '\n  union all\n  '.join(split_values) + ';')
    lines.append('')

lines.append('commit;')

OUT_SQL.write_text('\n'.join(lines), encoding='utf-8')
print(f'Wrote {OUT_SQL}')
print(f'Rows transformed: {len(rows)}')
